### PR TITLE
Suffix `$INODE64` not required in darwin/aarch64

### LINKED ISSUE #1269: Functions with `$INODE64` suffix not found on darwin/aarch64
Compiling on M1 fails with:

```
clang: warning: /usr/bin/clang: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
: error: /usr/bin/clang: Undefined symbols for architecture arm64:
: error: /usr/bin/clang:   "_fstat$INODE64", referenced from:
: error: /usr/bin/clang:       __Jjava_io_IO_1Util_IO_1GetLength__Ljava_io_FileDescriptor_2_J in IO_Util.o
: error: /usr/bin/clang:       __Jjava_io_IO_1Util_handleOpen__Lorg_qbicc_runtime_CNative_00024ptr_2Lorg_qbicc_runtime_CNative_00024c_1int_2Lorg_qbicc_runtime_CNative_00024c_1int_2_J in IO_Util.o
: error: /usr/bin/clang:       __Jsun_nio_ch_FileDispatcherImpl_size0__Ljava_io_FileDescriptor_2_J in FileDispatcherImpl.o
: error: /usr/bin/clang:   "_lstat$INODE64", referenced from:
: error: /usr/bin/clang:       __Jsun_nio_fs_UnixNativeDispatcher_lstat0__JLsun_nio_fs_UnixFileAttributes_2_V in UnixNativeDispatcher.o
: error: /usr/bin/clang:   "_stat$INODE64", referenced from:
: error: /usr/bin/clang:       __Jjava_io_UnixFileSystem_getBooleanAttributes0__Ljava_io_File_2_I in UnixFileSystem.o
: error: /usr/bin/clang:       __Jsun_nio_fs_UnixNativeDispatcher_stat1__J_I in UnixNativeDispatcher.o
: error: /usr/bin/clang:       __Jsun_nio_fs_UnixNativeDispatcher_stat0__JLsun_nio_fs_UnixFileAttributes_2_V in UnixNativeDispatcher.o
ld: error: /usr/bin/clang: symbol(s) not found for architecture arm64
clang: error: /usr/bin/clang: linker command failed with exit code 1 (use -v to see invocation)
error: Linker invocation failed: org.qbicc.machine.tool.CompilationFailureException: Compiler terminated with exit code 1
Compilation failed with 14 error(s) and 121 warning(s)
make: *** [Makefile:122: run] Error 1
```

The `$INODE64` suffix is not needed in darwin/aarch64 (as hinted in https://github.com/al45tair/mac_alias/issues/10). Once the suffix is removed, the code compiles fine.

For a proper fix, we probably need to adjust the `when` values to take into account both os and arch. I'll explore this.

### PR DESCRIPTION
**Pull request by galderz**
Fixes #1269 

Added `isMacOsAmd64` and `isMacOsArm64` build targets to separate different native registrations depending of env.

This worked locally on M1 machine. Let's see if CI `darwin/amd64` agrees.

### CODE REVIEW

File: runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java [hunk 1]
```diff
@@ -73,12 +73,21 @@ public static final class struct_stat64_ptr extends ptr<struct_stat64> {}
...
+    public static native c_int stat_inode64(const_char_ptr pathName, struct_stat_ptr statBuf);
+    @name(value = "fstat$INODE64", when = { Build.Target.IsMacOs.class, Build.Target.IsAmd64.class })
+    public static native c_int fstat_inode64(c_int fd, struct_stat_ptr statBuf);
+    @name(value = "lstat$INODE64", when = { Build.Target.IsMacOs.class, Build.Target.IsAmd64.class })
+    public static native c_int lstat_inode64(const_char_ptr pathName, struct_stat_ptr statBuf);
+    @name(value = "fstatat$INODE64", when = { Build.Target.IsMacOs.class, Build.Target.IsAmd64.class })
+    public static native c_int fstatat_inode64(c_int dirFd, const_char_ptr pathName, struct_stat_ptr statBuf, c_int flags);
+
+    @name(value = "stat", when = { Build.Target.IsMacOs.class, Build.Target.IsAarch64.class })
     public static native c_int stat(const_char_ptr pathName, struct_stat_ptr statBuf);
```
Comment (dmlloyd) [inline runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:86]: What are these for?

File: runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java [hunk 2]
```diff
@@ -73,12 +73,21 @@ public static final class struct_stat64_ptr extends ptr<struct_stat64> {}
...
-    @name(value = "fstat$INODE64", when = Build.Target.IsMacOs.class)
+    @name(value = "fstat", when = { Build.Target.IsMacOs.class, Build.Target.IsAarch64.class })
```
Comment (dmlloyd) [inline runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:87]:
```suggestion
    @name(value = "fstat$INODE64", when = { Build.Target.IsMacOs.class, Build.Target.IsAmd64.class })
```

Wouldn't this suffice to solve the problem?

Comment (galderz) [reply runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:87]: Well for darwin/aarch64 yeah... but amd64?

Comment (dmlloyd) [reply runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:87]: All this means is, when the platform is amd64, use the external name `fstat$INODE64` for this method instead of `fstat`. We don't need actual declarations for both, we just need the method to point to the correct function.

Comment (dmlloyd) [reply runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:87]: N.b. if no `@name` is given, then the name of the method is used.

**Comment by galderz** [comment]
Updated PR @dmlloyd

File: runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java [hunk 3]
```diff
@@ -73,12 +73,11 @@ public static final class struct_stat64_ptr extends ptr<struct_stat64> {}
...
-    @name(value = "stat$INODE64", when = Build.Target.IsMacOs.class)
     public static native c_int stat(const_char_ptr pathName, struct_stat_ptr statBuf);
-    @name(value = "fstat$INODE64", when = Build.Target.IsMacOs.class)
+
     public static native c_int fstat(c_int fd, struct_stat_ptr statBuf);
-    @name(value = "lstat$INODE64", when = Build.Target.IsMacOs.class)
+
     public static native c_int lstat(const_char_ptr pathName, struct_stat_ptr statBuf);
-    @name(value = "fstatat$INODE64", when = Build.Target.IsMacOs.class)
+
```
[the remark this answers is not in the document]
Comment (dmlloyd) [reply runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:81]: I think the appropriate fix is most likely to keep the `@name` annotations but add x86_64 to the list of conditions.

[the remark this answers is not in the document]
Comment (galderz) [reply runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:81]: Hmmm, you had mentioned removing the `@name` annotation so I thought you wanted that here too.

[the remark this answers is not in the document]
Comment (dgrove-oss) [reply runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java:81]: Yes, we need the name change annotation on x86_64 MacOS

**Review by dmlloyd — APPROVED** [review]
